---

landscape: syst

# this is the default environment color - you can override this on the command line or extra vars
color: blue

HostedZoneId: "Z0022698234MMVVFBQQN3"
HostedZoneName: "webrouter-nprd.aws-cloud.bu.edu"

# (issue- WAF and logbucket come from landscape so we
# need to keep the old style base&iam stacks around
# until we rebuild WAF)
#
LogBucket: "buaws-webrouter-base-syst-logbucket-7d3thxkupm79.s3.amazonaws.com"
LogPrefix: "cf-logs"

RedirectToHttps: "false"

WebACL: "203fb8d8-2300-4c2f-ba62-68c8a159ac34"
