---

- name: Set up ACM certificate requests
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # override the following with -e aws_profile=x if you want something other than default
    aws_profile: default

  tasks:

    - name: "Include our custom domain configurations"
      include_vars:
        file: "{{ item }}"
      with_first_found:
        - custom-domains.yml

    - name: "ACM configuration"
      include_tasks:
        file: "domain-acm.yml"
      loop_control:
        loop_var: domain
      loop: "{{ custom_domains }}"
